handlers = java.util.logging.ConsoleHandler

.level = INFO
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Surface every exception inside CXF rs-security-oauth2
org.apache.cxf.rs.security.oauth2.level = FINE
org.apache.cxf.rs.security.oauth2.services.level = FINE
org.apache.cxf.rs.security.oauth2.grants.level = FINE
org.apache.cxf.rs.security.oauth2.provider.level = FINE