theme: light
server:
  address: tcp://0.0.0.0:9091/
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: /config/server.key
    certificate: /config/server.crt
log:
  level: debug
  format: text
  file_path: /data/authelia.log
  keep_stdout: true
totp:
  disable: false
  issuer: authelia.com
  period: 30
  skew: 1
webauthn:
  disable: false
  display_name: Authelia Fuzzing
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
identity_validation:
  reset_password:
    jwt_secret: 6bb162780e67415529ae0ae7f4a559ba6b29a73e9c04ea2329063c99e9bc072e
authentication_backend:
  file:
    path: /config/users_database.yml
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16
access_control:
  default_policy: one_factor
  rules:
  - domain:
    - 127.0.0.1
    policy: bypass
    resources:
    - ^/api/health$
    - ^/api/oidc/.*
    - ^/api/state$
    - ^/api/configuration$
  - domain:
    - 127.0.0.1
    policy: one_factor
session:
  name: authelia_session
  secret: b4e328250622637e66e84f3293d61924eceaaee298f21eeb7a0e4db0973bf4db
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  cookies:
  - domain: 127.0.0.1
    authelia_url: https://127.0.0.1:9091
    default_redirection_url: https://127.0.0.1:7777
regulation:
  max_retries: 10
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: 877b5a265c087a855a61edbd932bc9899e6823c0d62f7f7090547b950455a623
  local:
    path: /data/db.sqlite3
notifier:
  disable_startup_check: true
  filesystem:
    filename: /data/notification.txt
identity_providers:
  oidc:
    hmac_secret: e51aed90259cf98c0acf5308daed129f001353b2d40b2da342cff5c1198f0c11
    jwks:
    - key_id: fuzz-key-1
      algorithm: RS256
      use: sig
      key: '-----BEGIN RSA PRIVATE KEY-----

        MIIJKQIBAAKCAgEAwIU4sMg7KLwpZYhteUF4H9q8yfVutNxb8Dle+IWRNQPKgVyg

        VmunLJL0qVh6YWuqEWie/J+qlohC4Rcoj6giFLPbTArYEADZjZ9RhUklc5Zy/dAA

        QlP7zdEjoJe6PBqLRGEbBdoZCdQoEexaTVBrrhGcQPDfdZUdqMiQC0zqvGmp4s41

        rGU8OR5DaisGkLPlSFDimNgq6rGXdF5/u/tV36qHpICvHMUpwf/ixZGh2zGrI7I5

        NuSsA8EB1JVXYSUhJSxZWEgxQsiKmFJPXyGAIUE0mKFafr3gnS93hrC8X8VmAjDD

        CLU/533FKhZrj6aDsHfQR2mqIu4poQbLVFFpsPJONz3iT2eEfr9vmTEe0g/nVQr/

        ql8k+lSyyO3T0zNBdEqOTBTRH56NUyDJ0apUbESGpFfvlO6s2xsayw1IWj2UJ2m9

        jGrG//Uy1DUBEwjqJfwyCr+S4D2IAzDI2e+MUeOaQLWQYHvwfXrtkFZ/0H3k/grB

        SATlnpnmx8da9u6/34A7PyXl1u8Z2y8BP5IUrT1U+DoIitPxj4NrUB21Bn410VwF

        fXblQl8EtATbEmE1mxUnnv+v6t/cGgyAZcKbqjYZBtgoJgr/4ncj3AXHJmULhRXB

        cd9H50E754p+0CJCs+zpYWajeF71Xl/MMD60JAk7QoU8VxNcl89zQ3W6JOMCAwEA

        AQKCAgAOQM61p91ZYrTd43/XXlV6ZkNb4GPV2AqmeljhpWHevu0bLrRgMZAq6KZc

        c0R8OfBZYZmDsn56rpPk/kXufNApIDe4JYVhie6RYZ4zc/rl19mjmOasAnO+BSHS

        HemX0Y9F/Lp3cHIyHBbrXMhCuRV/yaX72NlyZxvPBypC6+rlEB2XwRSQMt6GjAsJ

        rS3LQMZU2EgucLKctZE0+FoUnML60DFCqJROWPqCdmNfpSyKgd7dwbAitENX884i

        4vuZIZqWmfXzZ0TeYOKB7HYb4OsPizhNpISCpaQffwgmXKdVn9OxjdKirmiQxur1

        9rr346gURIqS/uutslw6o7oh//UHF4rYMMWh+P40jl9HaPTNAm71J7cjuFiDqd/E

        NPPNnmZiZr/n6jXGVOIxVk2rztT/j+2Proj+Ike5TP+49DoU1g/p31iQKjFXS9U9

        toAoDOSaqPVRwMvTOZquPNde4GqDJtmaQl/YmshATsCLu/SEMBY5i+X5ahpM+jeF

        AezsU1kNMuM79tfXVbbS0Fd7Tk3NwImCxkNYriXQsOLoNAcvdQ3gCSamQkRSpMtD

        MeEMVprMBIKOikweGLq5skM3x8Z9B5D9lpvzzgjSSKa07RRGhrc/CNePoL8jrIFg

        3Xm8uxUke3w/s3FqOg1TdLqer5Ja5P8rsQLACIoGlnrBcUKBwQKCAQEA+u8ESezu

        wQKUKmaelaMgZkBwt1isQ1+8HxCUeC+WFBh6MVRraLE5htn/ux2MB6VgIIwjIpPG

        A3u80K6McCLCStypUPyYcE/x2uoqE56KiBtKLisdDrEVduZZjNNFqRfiHWNzCIOR

        rfooo7lRhcNcP6ynl62kK77xLYjUZH+2q5CFqdMyfLFRYLlGLOQ1NqIFavxmzbyQ

        ZroYasW5tzudCFqrrJ5ubfUE1LooBa0SUtcTtPYAooxdCu7L8exupR8QD/TG4VI8

        dVKEwhzKI4uGsHtVALaH+CAGQ+/dSWUwcpaRLGeqGNKy9Z7V5Xf5XcAIdprT0QHX

        j08ItcxYhKa/eQKCAQEAxGhJxCpqpGM7l/+ZTWJ5xpEs/zfM9jEWaBqaW3ignqHd

        VhjQT2LFqYGc0Lng8ISAKuJBQZBS3IgXf8OD1wZNcOIgpFacdaMV2XbNY44V2WnK

        aqABavEyiR3EQfLZuI7XHYw4C3zteo2zOzIA88G5AzXuFI2OUUB5RHPwxwB80ZGr

        hBNE5qFOmhT/15Jms5tieYi5HJ7Dr8adyVB6YyE4siUqzTrFHsBI4LhKuRlpYwty

        8NYTBxo/Rw9d4VYFTvaLenQs/bgHBsPuaF2EEknI6adPhgbhBdKX/GW3KYlcvba2

        B5dJJ1iY6J95zqNjS0Qs6a4dOvVuP1qjH32OgJckOwKCAQEAtzo8GXbGR20In4Vb

        GsyIZeF77IT1FCUdilli7/dfUMEmyEpqO4HdDZi04P6MNzEMZfet2BurJPP/RSmP

        JnpbAKrrf1VSQgA+C6mcm8LSSNwUaG3Ww9mOYMmGbgv++5+S3f62Cmt3vl/BuPsi

        idfCzkPWBC0oiUDdfnBBFjkjO1dGImEyplYbo9LlaPYh3QiliB9ROb0Me9Y66gwC

        tcbzvRvn6x2saOHWazaa7roXfSHLJAHVKNvxPIBtrvMDP9LUubH0XqbbupdMlSjM

        ePPyn38O7HxcAFPx/z1wiZ03qRREYPY4//Mp9avLZ8kY7tm/1Erti9oaemwtYgIa

        SJIxkQKCAQBVHWDCWyNl4/8iaskTyRY+4BEg9RykoDc2nDjCZS8uL7VMp2o2zPYd

        9CZyKet6L+GfM/fVoubV3UBZxO/wkjGjNsuwjDw3mppQaHSvrRZ45qiqtnaG0sn0

        s+qmLcj+eyBsFKUBDX2Yu6mtgIj7GbvE0W1AiOvg+FDVQm1YwDRXWYp7rSIR1FvM

        2EbbM/2/3hm5029tILxrA2bDpFW1eeMpCIRY9hwQrIGoqRTwzDtoicCg8BTE4jID

        6HvluDKKurtNMOWCemrJGsXJgqVGi6U+5JvI2FhR/qaQ4b+Th4yiRnjyJzSzkWiK

        fvn5e8L/DidsiWDveQby+6NvdSj5PwabAoIBAQCCEX5Qn6quL55n5RZSMPJNMw1V

        3Kg+rFW7NOfsRFj+mQscPFQPset/VtbjB024ZqXuwpwWlZ77Mdwhib130k2T8pmq

        MZYWqx3c7oY5haDtIhjdCLIS0OzM8eDpjJzoF6vOtktQ0Eiv6QSxz0TmwpIgARlr

        /g1TDB8s6SylyCXxw2a3un/PGkVwZw/sVZSQ+KlVz9MpVvNODLAKrFXT/zWTMYfT

        ne3FQwllHtg9CPb5u+EaeWfAYhdS/pdk1G/i0U4jqpB8O6TMrXzXhvIl2opGBtii

        9cNK5tO6FUwDOVCYectAcgCOwY4aQ9FN/pi3glMYfkr3kwn+IUguQHsoeyQd

        -----END RSA PRIVATE KEY-----'
    cors:
      endpoints:
      - authorization
      - token
      - revocation
      - introspection
      - userinfo
      allowed_origins_from_client_redirect_uris: true
    clients:
    - client_id: fuzz-client
      client_name: OAuth Fuzzing Client
      client_secret: $plaintext$fuzz-client-secret
      public: false
      authorization_policy: one_factor
      require_pkce: false
      pkce_challenge_method: S256
      redirect_uris:
      - https://127.0.0.1:7777/callback
      scopes:
      - openid
      - profile
      - email
      - groups
      - offline_access
      grant_types:
      - authorization_code
      - refresh_token
      response_types:
      - code
      response_modes:
      - form_post
      - query
      - fragment
      token_endpoint_auth_method: client_secret_post
      userinfo_signed_response_alg: none
      consent_mode: implicit
